#backtraces_path = "/path/to/neovide_backtraces.log" # see below for the default platform specific location
fork = true
frame = "full"
idle = true
maximized = false
mouse-cursor-icon = "arrow"
neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = false
tabs = true
theme = "vim"
title-hidden = true
vsync = true
wsl = false

[font]
normal = ["Noto Sans Mono"]
size = 8.5
hinting = "full"
edging = "antialias"

[box-drawing]
# "font-glyph", "native" or "selected-native"
mode = "font-glyph"

[box-drawing.sizes]
default = [1, 4]  # Thin and thick values respectively, for all sizes

